// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7ha80Fcr1Y-dgmBIoNJc-z4ad_T0iFIg',
    appId: '1:1070659013311:web:6288cdeafdb9e67b0b140a',
    messagingSenderId: '1070659013311',
    projectId: 'chill-pill-sample',
    authDomain: 'chill-pill-sample.firebaseapp.com',
    storageBucket: 'chill-pill-sample.appspot.com',
    measurementId: 'G-J76QEZXXYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCpL-I2jvs-BDIGE_7nVN1m9gCgWtdsgA',
    appId: '1:1070659013311:android:29f9221a127f8acb0b140a',
    messagingSenderId: '1070659013311',
    projectId: 'chill-pill-sample',
    storageBucket: 'chill-pill-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCalGEj4oYi0m0NjEvcjIUPovk_nyw-DaA',
    appId: '1:1070659013311:ios:af5fbb80fa8032770b140a',
    messagingSenderId: '1070659013311',
    projectId: 'chill-pill-sample',
    storageBucket: 'chill-pill-sample.appspot.com',
    iosBundleId: 'com.example.chillpill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCalGEj4oYi0m0NjEvcjIUPovk_nyw-DaA',
    appId: '1:1070659013311:ios:af5fbb80fa8032770b140a',
    messagingSenderId: '1070659013311',
    projectId: 'chill-pill-sample',
    storageBucket: 'chill-pill-sample.appspot.com',
    iosBundleId: 'com.example.chillpill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7ha80Fcr1Y-dgmBIoNJc-z4ad_T0iFIg',
    appId: '1:1070659013311:web:13c785624c5925950b140a',
    messagingSenderId: '1070659013311',
    projectId: 'chill-pill-sample',
    authDomain: 'chill-pill-sample.firebaseapp.com',
    storageBucket: 'chill-pill-sample.appspot.com',
    measurementId: 'G-DSSWWNLV63',
  );
}
